### PR TITLE
build(ci): Add CI/CD pipeline

### PR DESCRIPTION
**Pull request by Centei**
Closes issue #15.

CI pipeline contains:

- Formatting (provided by clang-format)
- Linting (provided by clang-tidy)
- Conventional Commit Linting (provided by commitlint)

Formatting follows the main .clang-format file.
Linting follows the newly created .clang-tidy file. It uses clang-diagnostics, clang-analyzer, and cppcoreguidelines checks.

~~Further production testing _will_ be needed for this pull request.~~
Further CI pipeline testing will occur on this feature branch to avoid disruptions to main.

### CODE REVIEW

**Comment by absozero** [comment]
@Centei , Wondering if we can hold back on this issue in favor of also integrating a documentation linter (a "prose" linter), as well into this PR?

**Comment by absozero** [comment]
@Centei  I would very highly recommend for you to squash these test commits before the final PR review. Also, I am still working on preparing the documentation linter

**Comment by absozero** [comment]
Do not change any production resources such as global public-facing documentation without a code review, @Centei - Changing docs source back to previous source.

**Comment by Centei** [comment]
> Do not change any production resources such as global public-facing documentation without a code review, @Centei - Changing docs source back to previous source.

👍
Documentation was not changed. Complete CD testing will have to occur on main branch.

**Pull request merged**
